language: csharp
solution: TravisTest.sln
install:
  - nuget restore TravisTest.sln
script:
  - msbuild /p:Configuration=Release TravisTest.sln
  - mono ./packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll
